name: Update RSS Feed

on:
  schedule:
    - cron: '0 * * * *'  # Toutes les heures
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  update-feed:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        pip install feedparser feedgen requests
    
    - name: Run filter script
      run: python filter_rss.py
    
    - name: Move feed to root
      run: |
        mkdir public
        mv output/feed.xml public/feed.xml
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
